### ISSUE TITLE
Error Loading Asset CSS di Lokal

### ISSUE THREAD

**Issue by munirapp** [phpid-jakarta/phpid-online-learning-2020#14]
Ketika saya mencoba mengclone repository ke lokal, dan menjalankan script build `npm run build` lalu mencoba menlajankan script host lokal `npm run dev` ataupun `npm run devopen`. Selalu saja hasil pagenya tidak bisa meload file asset cssnya dengan baik. Apakah ada langkah2 yang terlewat? atau ada solusi untuk menangani masalah ini?

Screenshoot hasil running page

![image](https://user-images.githubusercontent.com/17497888/87027475-cc883d00-c20f-11ea-9f99-d81d48b56c8f.png)

![image](https://user-images.githubusercontent.com/17497888/87027555-e9247500-c20f-11ea-8802-b800b99fbf8c.png)

**Comment by munirapp** [comment]
Bisa di open lagi mas issuenya ini, soalnya setelah saya fetch skrip terbaru tampilan development-nya kembali error

![image](https://user-images.githubusercontent.com/17497888/88387601-67267580-cde5-11ea-9da9-b57e8c7126c4.png)

**Comment by mazipan** [comment]
Ada yang kesenggol Macy nya...
Kebanyakan tab nya...

**Comment by munirapp** [comment]
Untuk masalah bug/error pas dev mode udah solve mas, masalahnya ternyata di parcel, klo dev mode dan punya external assetnya baiknya jangan pake --public-url, referensinya dari sini:

https://github.com/parcel-bundler/parcel/issues/4678#issuecomment-638496223
