### ISSUE TITLE
Bug - position of button on dialog is not proper

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-online-learning-2020#20]
![Screenshot_20200724-190409_Chrome](https://user-images.githubusercontent.com/7221389/88389377-9ab2d100-cde0-11ea-95a1-d6f57dcebf40.jpg)

**Comment by munirapp** [comment]
Klo di run local resourcenya error lagi mas, tadi mau kuperbaki yang agak kurang jadi gak bisa test di local

**Comment by mazipan** [comment]
Ada yang kesenggol berarti.

**Comment by munirapp** [comment]
Ini macy sebenarnya versi npmnya, apa di require lewat node modules aja kali yah?

**Comment by mazipan** [comment]
![Screenshot_20200724-191957_Chrome](https://user-images.githubusercontent.com/7221389/88390564-b919cc00-cde2-11ea-8b18-057bc327be0d.jpg)

**Comment by mazipan** [comment]
Cobain aja

**Comment by munirapp** [comment]
Aneh juga yah padahal di editor indentasinya aman, kucoba cek lagi

![image](https://user-images.githubusercontent.com/17497888/88390966-d99a5400-cdeb-11ea-8669-9dc99e2c2ab6.png)

**Comment by mazipan** [comment]
Salah itu, Macy nya di luar if-else

**Comment by munirapp** [comment]
Oh Astaga oke2 baru paham, gagal fokus kirain masuk di vendor.less

**Comment by munirapp** [comment]
padahal kan js ya hahah

**Comment by mazipan** [comment]
Nah itu tau sendiri, pelan-pelan tracing nya.

**Comment by mazipan** [comment]
Btw, udah ta invite jadi maintener.
Bisa langsung direct push ke repo ini tanpa fork ya kalau mau.

**Comment by munirapp** [comment]
Tapi masih error tampilan lokanya mas, di console sih bilang error di main.js, apa perlu pakai babel yah?

![image](https://user-images.githubusercontent.com/17497888/88391397-b328e880-cdec-11ea-919b-5ca00f96e836.png)

**Comment by mazipan** [comment]
Pusing kan koding Jade? 😂🤭
Biar gak html mulu taunya 🤯

**Comment by munirapp** [comment]
Ha ha ha, manual mah saya ampun makanya betah di fw yang udah jadi aja

**Comment by mazipan** [comment]
Parcel by default sudah ada transpiler nya, gak perlu override lagi

**Comment by mazipan** [comment]
Cobain di hapus dulu cache parcel nya.

**Comment by munirapp** [comment]
Udah saya hapus tetep masih error

**Comment by mazipan** [comment]
Coba cek lagi dari PR terkahir, yang ragu2 di revert dulu.

**Comment by munirapp** [comment]
Oke kayaknya aman, tadi cuma geser indentnya macy

**Comment by munirapp** [comment]
Di prod aman mas, di localku masih error tampilannya, besok aja mungkin di lanjut

**Comment by munirapp** [comment]
Masalah error/bug load asset pas di development silahkan beralih kesini

https://github.com/phpid-jakarta/phpid-online-learning-2020/issues/14#issuecomment-663825105

**Comment by munirapp** [comment]
Untuk button modal sudah saya perbaiki stylenya

![image](https://user-images.githubusercontent.com/17497888/88455566-e29d2b00-cea8-11ea-9824-a7a362ffbe99.png)
