### ISSUE TITLE
Macy recalculate method should call right after image loaded.

### ISSUE THREAD

**Issue by nyancodeid** [phpid-jakarta/phpid-online-learning-2020#23]
Issue ini untuk membahas dimana dan kapan seharusnya method `window.__macy.recalculate(true);` dipanggil. Karena untuk sekarang method ini dipanggil ketika terdeteksi Intersect atau scrolling. Ketika pengguna melakukkan scroll ke tengah konten dan diam sesaat untuk menunggu gambar dimuat, tata letak dan tampilan mulai acak karena ukuran gambar yang berbeda-beda.

Tampilan layout masonry yang berantakan ini terjadi karena recalculate (mengatur kembali posisi dan layout masonry) dipanggil hanya saat pengguna melakukkan aksi scroll.

###  Suggestions for improvement
Untuk mengatasi layout yang berantakan akibat gambar yang dimuat berbeda-beda ukuran maka seharusnya method ini dipanggil tepat setelah gambar berhasil dimuat. Untuk mengatur layout masonry tepat setelah gambar tampil sehingga tampilan layout bisa langsung diperbaiki. 

### Code References
https://github.com/phpid-jakarta/phpid-online-learning-2020/blob/fe88deacbb0c4d88f39b65ac243096cc5138282b/src/components/CardItem.svelte#L14-L19

Terima kasih.

**Comment by mazipan** [comment]
Ini sempat gak kalau bantuin benerin @nyancodeid ?

**Comment by nyancodeid** [comment]
Bisa, kalau senggang nanti saya bikin PR.

**Comment by mazipan** [comment]
Cool, thanks.
Let me know kalau memang gak sempat.

**Comment by nyancodeid** [comment]
Got it
